name: Links check

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
  schedule:
    - cron: '30 3 * * 4' # Run every Thursday at 3:30 AM UTC

jobs:
  linkChecker:
    uses: Infineon/makers-devops/.github/workflows/check_links.yml@main